# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/_protobuf/script_data.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/_protobuf/script_data.proto\x12\x08messages\"\xf6\x01\n\x08\x46romIPCM\x12\x32\n\x0bscript_data\x18\x01 \x03(\x0b\x32\x1d.messages.FromIPCM.ScriptData\x1a\xb5\x01\n\nScriptData\x12\x11\n\tscript_id\x18\x01 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\".messages.FromIPCM.ScriptData.Data\x1a\x62\n\x04\x44\x61ta\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x13\n\x0bstatus_code\x18\x04 \x01(\r\x12\x12\n\nis_ignored\x18\x05 \x01(\x08\"\xdc\x01\n\x06ToIPCM\x12\x30\n\x0bscript_data\x18\x01 \x03(\x0b\x32\x1b.messages.ToIPCM.ScriptData\x1a\x9f\x01\n\nScriptData\x12\x11\n\tscript_id\x18\x01 \x01(\t\x12.\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32 .messages.ToIPCM.ScriptData.Data\x1aN\n\x04\x44\x61ta\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x13\n\x0bstatus_code\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src._protobuf.script_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FROMIPCM']._serialized_start=46
  _globals['_FROMIPCM']._serialized_end=292
  _globals['_FROMIPCM_SCRIPTDATA']._serialized_start=111
  _globals['_FROMIPCM_SCRIPTDATA']._serialized_end=292
  _globals['_FROMIPCM_SCRIPTDATA_DATA']._serialized_start=194
  _globals['_FROMIPCM_SCRIPTDATA_DATA']._serialized_end=292
  _globals['_TOIPCM']._serialized_start=295
  _globals['_TOIPCM']._serialized_end=515
  _globals['_TOIPCM_SCRIPTDATA']._serialized_start=356
  _globals['_TOIPCM_SCRIPTDATA']._serialized_end=515
  _globals['_TOIPCM_SCRIPTDATA_DATA']._serialized_start=194
  _globals['_TOIPCM_SCRIPTDATA_DATA']._serialized_end=272
# @@protoc_insertion_point(module_scope)
